### PR TITLE
Apply fixes from StyleCI

### PR DESCRIPTION
**Pull request by Sweepr**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://github.styleci.io).

---

For more information, click [here](https://github.styleci.io/analyses/Q3dbMj).

### CODE REVIEW

**Comment by Sweepr** [comment]
@mesa57 

StyleCI reported a large number of fixes it wants to push that spans a whooping 83 files  : https://github.com/spotweb/spotweb/pull/814/commits/29f7a32fd3ff5b9169bb1d28093a882cefbb7a3e

Could you have a look this?

**Comment by mesa57** [comment]
Look predomantly space indent issues. Has something changed in styleci options ?
And of course you could skip this.

**Comment by Sweepr** [comment]
> Look predomantly space indent issues. Has something changed in styleci options ? And of course you could skip this.

The .scrutinizer.yml file has been changed about 2 month's ago by me because of PHPCS having some issue's with PHPunit, so i removed it from the .yml file, could be StyleCI got stricter because of that?

Although most seem to be spacing changes, there are also parentheses removed in some files so i'd thought it's good to double check with you before we merge any breaking changes.

If you agree we can merge this?

**Comment by mesa57** [comment]
Just merge and perform some testing.

**Pull request merged**
