### PR TITLE
Correction search for TV series in newznabapi.php to  get correct lis…

### PR DESCRIPTION
**Pull request by mesa57**
Needed fpr correct list for Sickbeard and Sonarr

### CODE REVIEW

**Comment by BasPost** [comment]
Hmm.... I have a problem with Sonarr and Spotweb, Sonarr gives me always an error with searches, while Couchpotato is working well.
I hope this will be merged soon.

**Comment by mesa57** [comment]
Any reason why this pull request is not merged ?

**Comment by buurman** [comment]
Please merge these changes

**Comment by Sweepr** [comment]
Could you also create a pull request for the media branch?
When done, i'll merge the request,

**Comment by mesa57** [comment]
If I create a pull request on the media branch you cannot merge automaticly.
Do you want it anyway ?

**Comment by Sweepr** [comment]
Ok, then leave this for now.. and i will see if i can edited this manually.

**Comment by mesa57** [comment]
Sweepr,
 
I will create a pull request, you can easily see what has been changed.
You can then decide what to do.
 
Greetz, mesa57 (jan)

  _____  

Van: Sweepr [mailto:notifications@github.com] 
Verzonden: dinsdag 3 november 2015 20:25
Aan: spotweb/spotweb
CC: Jan
Onderwerp: Re: [spotweb] Correction search for TV series in newznabapi.php
to get correct lis. (#89)



Ok, then leave this for now.. and i will see if i can edited this manually.

-
Reply to this email directly or view it
<https://github.com/spotweb/spotweb/pull/89#issuecomment-153461456> on
GitHub.
<https://github.com/notifications/beacon/AGDmhXQJOtTDxbRnajOKkrKejPkAliPRks5
pCQGPgaJpZM4F0-An.gif> 

  _____  

Geen virus gevonden in dit bericht.
Gecontroleerd door AVG - www.avg.com
Versie: 2015.0.6173 / Virusdatabase: 4457/10942 - datum van uitgifte:
11/03/15

**Comment by Sweepr** [comment]
Ok thanks.

**Comment by mesa57** [comment]
I can fork the media branch and apply the changes there too.
But then you have to wait for the weekend, because that takes more time.

  _____  

Van: Sweepr [mailto:notifications@github.com] 
Verzonden: dinsdag 3 november 2015 20:39
Aan: spotweb/spotweb
CC: Jan
Onderwerp: Re: [spotweb] Correction search for TV series in newznabapi.php
to get correct lis. (#89)



Ok thanks.

-
Reply to this email directly or view it
<https://github.com/spotweb/spotweb/pull/89#issuecomment-153464897> on
GitHub.
<https://github.com/notifications/beacon/AGDmhbki8Sh5FnVum4vmEvatki68cT7Jks5
pCQTOgaJpZM4F0-An.gif> 

  _____  

Geen virus gevonden in dit bericht.
Gecontroleerd door AVG - www.avg.com
Versie: 2015.0.6173 / Virusdatabase: 4457/10942 - datum van uitgifte:
11/03/15

**Comment by Sweepr** [comment]
Sure, no problem. there is no rush, take your time

**Pull request merged**
