### PR TITLE
Delete NMA notification service, as NMA is down since 2018.

### PR DESCRIPTION
**Pull request by CptChaos**
Deleting the code that was used to send notifications to Notify My Android, as it's down since `2018-05-24` officially.
Due to the way the project has been set-up, I had to to a `composer dump-autoload` as well, which caused the updates to the composer files.

I know this PR isn't done yet, as far as I can see, only the settings need to be removed from the database, but haven't figured that out yet. The rest has been done already, I believe. Any help with it would be appreciated.

### CODE REVIEW

**Comment by Sweepr** [comment]
@CptChaos 
Thanks for the PR, i will review as soon as i find some spare time, one question: why did you have to do `composer dump-autoload` exactly ? because `composer remove uskr/nma-php` also will update the autoload files. 

```
composer remove uskr/nma-php
Loading composer repositories with package information

Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 1 removal
  - Removing uskr/nma-php (v0.0.4)

Writing lock file
Generating autoload files
```

**Comment by mesa57** [comment]
Currently I do have no time to review.

**Comment by CptChaos** [comment]
I removed the package manually and my IDE (PhpStorm) noticed the references. So afterwards I did a `composer dump-autoload` to update the autoloader.

**Comment by Sweepr** [comment]
> 
> 
> @Sweepr I removed the package manually and my IDE (PhpStorm) noticed the references. So afterwards I did a `composer dump-autoload` to update the autoloader. In the end, the result is the same as removing through CLI and update the autoloader automagically.
> 
> And as said, I only need to remove the settings in the database, but haven't found it yet. If I could get some guidance on that, that would be appreciated.
> 
> Just wondering; why are the composer packages commited as well anyway? The vendor folder should be none existing (in the repository, through `.gitignore`) and composer should handle it all. That way, there's no need to commit anything from the `vendor` folder, nor have autoloaders and other composer stuff committed, as it should be handled locally, except for `composer.json` and `composer.lock`. ;)
> 
> EDIT:
> I also committed another minor change to the `lib/notifications/Notification_Factory.php`, which had still some `nma` references which were found by the Scrutenizer test.

Database settings are set in here:

https://github.com/spotweb/spotweb/blob/86b6b8492938a3e22ae9023cf40eaf7fe06c421b/lib/services/User/Services_User_Record.php#L449

And here:

https://github.com/spotweb/spotweb/blob/703307834abb585cb987fb6c04777620aa09d61f/lib/services/Upgrade/Services_Upgrade_Users.php#L437

https://github.com/spotweb/spotweb/blob/703307834abb585cb987fb6c04777620aa09d61f/lib/services/Upgrade/Services_Upgrade_Users.php#L303


image

Also don't forget to update the bootstrap:

**Comment by CptChaos** [comment]
@Sweepr Thanks for the help, I made the suggested fixes! :)

**Comment by Sweepr** [comment]
@CptChaos 

If i find a free time-slot will do a full review/test in the coming week, if no issue are found i will merge the PR.

**Comment by Sweepr** [comment]
I have done a small review an noticed that your composer.lock isn't updated, see:: https://github.com/CptChaos/spotweb/blob/147d0e7573ad8599c1daaee25b1eaf28b3d2951d/composer.lock#L1861

Probably this is because you have removed the package manually instead of using : composer remove uskr/nma-php

And i noticed are some changes made to the composer/vendor folder that i just cannot seem to place, for example these two new files that are introduced: 

https://github.com/CptChaos/spotweb/blob/delete-nma-notification-service/vendor/composer/platform_check.php
https://github.com/CptChaos/spotweb/blob/delete-nma-notification-service/vendor/composer/InstalledVersions.php

Why are they introduced and where do they come from?

Did you perhaps make these edits to an installed Spotweb instance?, if yes i would suggest to pull the Develop branch again, do not run `install.php`

Do:
`composer remove uskr/nma-php`

Edit the files need to remove `nma` 

And make a new PR.

**Comment by CptChaos** [comment]
Thanks for the review, @Sweepr the two files you mentioned (`platform_check.php and `InstalledVersions.php`) are files generated by Composer 2.0 which I use on my system. And I forgot to push the `composer.lock` file.

**Comment by CptChaos** [comment]
Made a new commit, to correctly remove the `usk/nma-php` package. The files for Composer 2.0 are therefor updated again.

**Comment by Sweepr** [comment]
@CptChaos

I wasn't aware you were using Composer v2 as that caused some confusion,  me and Mesa57 are still using Composer v1, but that souldn't matter since v1 and v2 should be backwards compatible.

I'll test the PR again tomorrow and if ok it will be merged.

Thanks for the effort.

**Comment by CptChaos** [comment]
Thanks for the reviews and the feedback!

**Comment by Sweepr** [comment]
I reviewed the PR once again by pulling your delete-nma-notification-service branch, then went along the install.php and got a nice `'Spotweb contains updated global settings settings. Please run 'bin/upgrade-db.php' from a console window'` message.

Then went over to CLI to do a `php upgrade-db.php` but got presented by this:

```
php upgrade-db.php
PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.2.5". You are running 5.6.11. in /volume1/web/develop/vendor/composer/platform_check.php on line 25

Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.2.5". You are running 5.6.11. in /volume1/web/develop/vendor/composer/platform_check.php on line 25
```

Now i must inform you that there are still a lot of users that run Spotweb on PHP lower then 7.2.5, so this isn't going to work for those users forcing them into updating.

So sadly i cannot merge this PR.

**Comment by Sweepr** [comment]
@mesa57 

This PR will not work on anything lower then PHP 7.2.5, please advise what to do.

Should we break users instances and force them to upgrade to a higher PHP version by upping our lowest supported PHP version to 7.2.5? or should we keep PHP 5.6 as lowest supported version?

**Comment by mesa57** [comment]
No, not fort his change which has no added functionality.
So users will gain nothing, only lose if they have to upgrade.


-- 
Deze e-mail is gecontroleerd op virussen door AVG.
http://www.avg.com

**Comment by CptChaos** [comment]
Ah, I missed that part indeed, my apologies. On the other hand, I also don't think to keep support for older versions of PHP isn't wise either. Most of the older versions aren't even supported by PHP itself anymore and become a bigger security risk day by day. Eventually it's just a matter of time when the leaks are actively being used, which I would not want to be part of, because I would still "support" older versions of PHP. In fact, PHP versions 5.6, 7.0, 7.1 and 7.2 don't have any support anymore at all! See also https://www.php.net/supported-versions.php.

I'll make a new branch and new PR, which just doesn't do anything on the minimum for now, so the version compatibility does not break. But keep in mind that 'because users are having older versions of PHP', to my opinion isn't a valid reason to keep old versions still supported at all. It means a bigger security risk day by day already and also keeps tech-debt in the project, which is also something one should not want to my opinion. ;) One example is Notify My Android support still in Spotweb, when Notify My Android itself has been shutdown back in 2018, 3 years ago. ;)

**Comment by Sweepr** [comment]
@cptchaos,

No need to create a new PR for it, i already merged this using: https://github.com/spotweb/spotweb/pull/661

About the PHP version's you are right and i do agree, but their are NAS users (still) running 5.6.40 and run Spotweb on their own local network using outdated PHP versions, main reason we still support it is because NAS software development is running so far behind that as of **2019-05-28** Synology did their last update to version **5.6.40**.

Altough ofcourse we advise to update to a newer version of PHP, spotweb run's fine on PHP 5.6 up to PHP 8.0.2

https://www.synology.com/en-global/releaseNote/PHP5.6?model=DS216j

**Comment by mesa57** [comment]
I think to the end of coming year we can deprecate php 5.6 support, but not now, and not for this change.

**Pull request closed without merging**
