### PR TITLE
Move media branch forward up to master

### PR DESCRIPTION
**Pull request by dsadsdadsadsadsds**
Hi There,

This is a friendly pull request which basically merged all commits from _master_ back in to the media branch. This is done using a very crude way so some things might be broken.

My suggestion would be to test this version, repair/fix where necessary but the aim should be to merge the media branch into master as soon as possible as it is more advanced.

### CODE REVIEW

**Comment by mesa57** [comment]
And who should test this ? The media branch is used by few people ...

**Comment by Sweepr** [comment]
I could give it a try...

**Comment by Sweepr** [comment]
During install:

/install.php?page=4

Fatal error: Cannot redeclare Dao_Mysql_Factory::setCacheStore() in C:\xampp\htdocs\spotweb2\lib\dao\Mysql\Dao_Mysql_Factory.php on line 11

**Comment by Sweepr** [comment]
Trying to retrieve:

**Comment by mesa57** [comment]
Pffff...

**Comment by Sweepr** [comment]
So far everything else looks ok, under settings/performance i do see two times:

`Enable imagepreview in spot overview`

**Comment by Sweepr** [comment]
Not sure where to fix this 

Fatal error: Call to undefined method Dao_Mysql_Factory::getCacheStore()

**Comment by Sweepr** [comment]
@dsadsdadsadsadsds 

Could you fix the getCacheStore error? probably in Dao_Mysql_Factory.php a typo has been made where two times 

public function setCacheStore(Dao_CacheStore $cacheStore) {
        $this->_cacheStore = $cacheStore;
    } # setCacheStore

public function setCacheStore(Dao_CacheStore $cacheStore) {
        $this->_cacheStore = $cacheStore;
    } # setCacheStore

Are set causing.

Fatal error: Cannot redeclare Dao_Mysql_Factory::setCacheStore() in C:\xampp\htdocs\spotweb2\lib\dao\Mysql\Dao_Mysql_Factory.php on line 11

After removing one of the double's and trying to retrieve it tell's me:

Fatal error: Call to undefined method Dao_Mysql_Factory::getCacheStore() in C:\xampp\htdocs\spotweb2\lib\dao\Mysql\Dao_Mysql_Factory.php on line 36

**Comment by mesa57** [comment]
btw. that code belongs to the non commited / tested changes in the cache from dasd
Are you trying to merge everything ?

**Comment by Sweepr** [comment]
Yes, i merged the pull request, downloaded the branch, and unmerged.

**Comment by dsadsdadsadsadsds** [comment]
Yes, it belongs to the pluggable cache store implementation, but it still enables the current trusted and tested flat file cache store.

Let me try to fix the errors given.

Would you be able to re-open this PR?

**Comment by Sweepr** [comment]
After merge and revert the pull request is gone, so you have to make a new pull request

**Comment by dsadsdadsadsadsds** [comment]
Ok. If you want to, you could clone my fork first and only accept the PR once its a bit stead. I'll open a new PR for tracking any issues.

**Comment by Sweepr** [comment]
Ok, that's a good idea

**Comment by Sweepr** [comment]
So i have now cloned your fork,. about to test it and i will report back.

I saw you didn't yet fix this ?

two times:

Enable imagepreview in spot overview

Removing:

<dt><label for="editsettingsform[imageover_subcats]"><?php echo _('Enable imagepreview in spot overview'); ?></label></dt>
<dd><input type="checkbox" name="editsettingsform[imageover_subcats]" <?php if ($this->_settings->get('imageover_subcats')) { echo 'checked="checked"'; } ?>></dd>

from lines 243-244 from templates/we1rdo/editsettings.inc.php fixes that.

**Comment by Sweepr** [comment]
Retrieving another attempt:

Catchable fatal error: Argument 1 passed to Dao_Mysql_Factory::getCacheStore() must implement interface Dao_CacheStore, none given, called in C:\xampp
\htdocs\spotweb2\lib\dao\Mysql\Dao_Mysql_Factory.php on line 40 and defined in C:\xampp\htdocs\spotweb2\lib\dao\Mysql\Dao_Mysql_Factory.php on line 11

**Comment by dsadsdadsadsadsds** [comment]
Are you sure that is the clone of my current fork? As https://github.com/dsadsdadsadsadsds/spotweb/blob/media/lib/dao/Mysql/Dao_Mysql_Factory.php#L11 does not contain anything of the cache store.

Perhaps you are in the master branch of this fork and not in the media branch?

**Comment by Sweepr** [comment]
The branch i downloaded is spotweb-media.zip, but i thought i copied the change's in the lib folder, which were not.. so i copied those and now it's working.

Retrieve is running

**Comment by Sweepr** [comment]
So i finished the installation and retrieval of spots succesfully using your media branch.

What is the next thing to test?

So now it should be possible to remove a spot that is posted using spotweb by the same user correct?

**Comment by mesa57** [comment]
No, that is not supported (yet). For the time being only the personal dispose messages from spotnet 1.8.5.x and spotnet V2 are processed to prevent duplicate spots in the list.

**Comment by dsadsdadsadsadsds** [comment]
Some things you might want to test:
* Are the collections properly created?
* Has performance not been detoriated ?
* Is the cache filling correctly

If all this is in order, I would try to gather more regular testers (especially people upgrading frm the master branch) to ensure the upgrade process is smooth.

If this all works out, a merge into master would be in order. We should however re-check the major version and minor versions in the Spotweb configuration to ensure we enforce a settings upgrade.

**Comment by mesa57** [comment]
I already asked @wally73, who reported a problem as he overwrote his media branch checkout, to test. I do not know of any other people using the media branch.

**Comment by Wally73** [comment]
@CptChaos check this too please ;)

**Comment by CptChaos** [comment]
I overwrote the files, made a pull request already for it: #146

**Comment by Sweepr** [comment]
@dsadsdadsadsadsds 



Some things you might want to test:

    Are the collections properly created? <- Yes.
    Has performance not been detoriated ? <- No.
    Is the cache filling correctly <- Yes.

If all this is in order, I would try to gather more regular testers (especially people upgrading frm the master branch) to ensure the upgrade process is smooth.

If this all works out, a merge into master would be in order. We should however re-check the major version and minor versions in the Spotweb configuration to ensure we enforce a settings upgrade.

**Comment by dsadsdadsadsadsds** [comment]
That's good to know, this would basically mean the changes do not negatively affect the system. Could you try to gather some more testers?

I'll open up a new PR so we can properly integrate it into master.

**Comment by Sweepr** [comment]
Is this correct?

Revert "Revert "Move media branch forward up to master"" 

https://github.com/spotweb/spotweb/pull/156

**Comment by dsadsdadsadsadsds** [comment]
Just a heads up, I merged all recent changes from @mesa57 back in to my fork so the media branch should be fully up to date now.

**Pull request merged**
