### PR TITLE
Implement multiple cache stores

### PR DESCRIPTION
**Pull request by dsadsdadsadsadsds**
Just before the last major release of Spotweb, the cache was migrated from a database cache to a flat filestore cache.

This flat filestore caches in nested directories the actual files and stores the metadata on disk. While this is an improvement over abusing the database for this amount of data, it does take its toll on both diskspace as filesystem performance if you have a full Spotweb system.

Attached in this pull request are several parts: 
- Migrate the actual storing of the cache into a seperate cache store (interface Dao_Base_CacheStore)
- Implementation of the current FlatFile Cache Store
- Example implementation of a Zipped file store

The Zipped cache store stores up to 1000 files into a single ZIP file archive. While this is mostly not done for compression (eg: JPG's dont compress all that well, although NZB's do) it is mostly done to reduce the amount of inode's on the filesystem and to reduce the blocksize overhead of the filesystem. It's been runing for more than a year on my system and reduced the impact of the cache immensely.

The ZippedCacheStore piece is also the default in this pull request. An example script is provided which migrates the older cache store to the Zipped cache store.

---

ToDo:
- Test. test it properly. The original code is based on the mediainfo branch and i just copied and pasted into the Github web ui so i might have forgotton some parts.
- Apply this patch to the mediainfo branch as well.
- Make the cache store configureable from within the UI.
- Test the migration script properly.
- Make sure the actual cleanup of empty directories work.

### CODE REVIEW

**Comment by mesa57** [comment]
You say this needs testing. I agree. We should not merge a pull request before it has been tested properly. I already had to undo a merge before, so I think our policy should be not to merge untested code into the main branch.

**Comment by dsadsdadsadsadsds** [comment]
Correct, i just opened this PR to make anyone interessted aware of this change.

I'm basically just throwing this code out there -- i think it can make a lot of people happy, but it needs some extra polishing - I'm unable to do that myself unfortunately, but perhaps somewhere is willing to take this on.

One thing which might be a good starting point is to clone my fork, change the default (in Bootstrap.php) cachestore back to a flat file store and see if everything just keeps chugging along.

When it does that, I would suggest to merge, and then later on introduce the ZipCacheStore

**Comment by mesa57** [comment]
I thank you for proposa a creative change. But on this moment, the spotweb development team has been minimised. Even my time is very limited, as I am working on other releases too.
So, you are welcome to push development a little bit.

**Comment by Sweepr** [comment]
I have setup a daily cronjob using tmpwatch, what this does is delete files that have not been accessed for over 24 hours, (or set to your desire), this has also been running for over 2 years now and has kept the inode use and overhead cache use to a minimum.

0 1 * * * /usr/bin/tmpwatch -maf 24 /home/public_html/spotweb/cache > /dev/null 2>&1

**Comment by dsadsdadsadsadsds** [comment]
I have forwarded this pull request to include the latest changes

**Comment by Fossil01** [comment]
Any update on this?

**Comment by mesa57** [comment]
No, somebody has to do exhausted testing on that pull request.

**Comment by mesa57** [comment]
If I look at the request a sqlite change was ignored.

**Comment by Sweepr** [comment]
I spend the last 1,5 hour on this but failed to get it working and gave up.

I downloaded the branch **https://github.com/dsadsdadsadsadsds/spotweb.git** and tried to make it running but the first issue i encountered was: 

`Fatal error: Cannot redeclare Dao_Mysql_Factory::setCacheStore() in C:\xampp\htdocs\das\lib\dao\Mysql\Dao_Mysql_Factory.php on line 11`

Which turn out to be a typo in Dao_Mysql_Factory.php where it reads: 

`
<?php

 class Dao_Mysql_Factory extends Dao_Factory {
     private $_conn;
     private $_cacheStore;

    public function setCacheStore(Dao_CacheStore $cacheStore) {
        $this->_cacheStore = $cacheStore;
    } # setCacheStore

    **public function setCacheStore(Dao_CacheStore $cacheStore) {
        $this->_cacheStore = $cacheStore;
    } # setCacheStore**  
`
The BOLD is double, and causes an issue, which needs to be resolved in order to make things work properly.

After that i tried to run retrieve.php, and ran into another issue:

Removing Spot information which is beyond retention period,
Fatal error: Declaration of Dao_Base_Cache::saveSpotImageCache() must be compatible with Dao_Cache::saveSpotImageCache($resourceId, $metadata, $content, $performExpire) in C:\xampp\htdocs\das\lib\dao\Base\Dao_Base_Cache.php on line 2


Dao_Base_Cache.php reads: 
`function saveSpotImageCache($resourceId, $metadata, $content, $isErrorImage, $performExpire) {`

Where file Dao_Cache.php reads:
`function saveSpotImageCache($resourceId, $metadata, $content, $performExpire);`

Which should be: 
`function saveSpotImageCache($resourceId, $metadata, $content, $isErrorImage, $performExpire);`

Then:

# php retrieve.php
Removing Spot information which is beyond retention period,
Catchable fatal error: Argument 1 passed to Dao_Mysql_Factory::getCacheStore() must implement interface Dao_CacheStore, none given, called in C:\xampp
\htdocs\das\lib\dao\Mysql\Dao_Mysql_Factory.php on line 40 and defined in C:\xampp\htdocs\das\lib\dao\Mysql\Dao_Mysql_Factory.php on line 11



Too many error's and glitches in the "supposed working branch" this needs reviewing from @dsadsdadsadsadsds , and this branch does not have the composer update's yet.

**Comment by mesa57** [comment]
@Sweepr : Thank you for testing. Again a pull request which cripples spotweb :disappointed:

**Comment by Sweepr** [comment]
@mesa57 Seems i didn't read properly.. this 

I downloaded the 'Master branch' not the 'Media branch'.

So i went along and downloaded https://github.com/dsadsdadsadsadsds/spotweb/archive/media.zip

Instgall went fine, went to /lib/bootstrap.php and changed line 42

`$daoFactory->setCacheStore(new Dao_Base_FlatCacheStore($settings->get('cache_path'))); `

Into:

`$daoFactory->setCacheStore(new Dao_Base_ZipCacheStore($settings->get('cache_path'))); `

Ran the migrate-cache3.php

`c:\xampp\htdocs\dasmedia
# php migrate-cache3.php
Migrating cache content, items 0 to 1000, done.
Removing old and empty cache directories (can take a while)...
Scanning directory: .\cache\image\ (level: 0)
Scanning directory: .\cache\nzb\ (level: 0)
Scanning directory: .\cache\stats\ (level: 0)
Scanning directory: .\cache\web\ (level: 0)
Scanning directory: .\cache\translatedcomments\ (level: 0)
Scanning directory: .\cache\translatertoken\ (level: 0)
Updating schema..(pdo_mysql)`

And retrieving as i'm writing this.

I'll keep testing and report back with my findings, in the meanwhile i will see if i can figure out what's bugging the Master from working with the ZipCache as the Media branch from @dsadsdadsadsadsds seems to be working just fine.

If and when i get the Master branch working using the ZipCache i'll need see if i can get it to work under the latest Master using the composer.

Keep you updated in this thread.

**Comment by Fossil01** [comment]
What's the diff between the two branches

**Comment by Sweepr** [comment]
@Fossil01 

Checkout the first comment by me in the thread: https://github.com/spotweb/spotweb/issues/202

**Comment by Sweepr** [comment]
Hihi, i got the Master branch working using ZipCache too..

**Comment by mesa57** [comment]
@Sweepr : could you contact me on mesa57 (at) hotmail (dot) com ?

**Comment by Sweepr** [comment]
@mesa57  Done.

**Comment by dsadsdadsadsadsds** [comment]
If you really are eager to base these changes upon the master branch, please make sure it is properly reviewed first before you merge.

The ZippedCacheStore feature was and is exhaustively tested by me so I know it is correct, but merging it into a diverged codebase is not correct :)

**Comment by Fossil01** [comment]
Well my install somehow got massively fucked. It's a public install, should I install master or media branch.

**Comment by mesa57** [comment]
Depends on what you had previously installed. But normally it should be the master branch.

**Comment by MrHappy** [comment]
Is this PR dead in the water, 'cause I would like to have some more diskspace available... ;)

**Comment by mesa57** [comment]
Closed due to conflicting files.

**Pull request closed without merging**
