### PR TITLE
Check for empty string before removing comma's

### LINKED ISSUE #652: Spotweb crashes after latest updates to php files
On Sunday 17th of january, there have been some updates which cause the error message below, when running git pull

There have SpotWeb v0.68.32.33 on PHP v7.2.34 crashed

Fatal error occured retrieving reports:
  42000: 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1

#0 /var/www/html/spotweb/lib/dbeng/dbeng_pdo.php(86): dbeng_pdo->exec('DELETE FROM com...', Array)
#1 /var/www/html/spotweb/lib/dao/Base/Dao_Base_Comment.php(305): dbeng_pdo->modify('DELETE FROM com...')
#2 /var/www/html/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(636): Dao_Base_Comment->removeComments(Array)
#3 /var/www/html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(238): Services_Retriever_Spots->process(Array, '3485018', 3485124, 1610976605.3197)
#4 /var/www/html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(339): Services_Retriever_Base->loopTillEnd(3485124, '5000')
#5 /var/www/html/spotweb/retrieve.php(142): Services_Retriever_Base->perform()
#6 {main}**Describe the bug/issue**
 - A clear and concise description of what the bug is.

**To Reproduce**
1.  start commandshell , run command 'git pull'

**Expected behavior**
I was expecting the following message: '**Already up-to-date**.'

**Screenshots**
see error mesaage

**Desktop (please complete the following information):**
 - OS: [Windows 10 version 2004 OS build 19041.685]
 - Browser [mozilla firefox]
 - Spotweb Version [v0.68.32.33]
 - Which branch  (Develop)
 -  PHP version PHP v7.2.34
 -  Device information (Virtual machine Centos 7)

### PR DESCRIPTION
**Pull request by muis**
Check for empty string before removing comma's, fixes #652

### CODE REVIEW

**Comment by Sweepr** [comment]
I tested this without: https://github.com/spotweb/spotweb/pull/654 but still crashes.


Retrieving 2750552 till 2755553 (parsed: 368, in DB: 4633, signed: 253, invalid: 113, rtntn.skip: 0, mod: 2, full: 0, total: 5001)

SpotWeb v0.68.32.33 on PHP v7.4.14 crashed

Fatal error occured retrieving reports:
  42000: 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1

#0 /home/public_html/lib/dbeng/dbeng_pdo.php(86): dbeng_pdo->exec('DELETE FROM com...', Array)
#1 /home/public_html/lib/dao/Base/Dao_Base_Comment.php(312): dbeng_pdo->modify('DELETE FROM com...')
#2 /home/public_html/lib/services/Retriever/Services_Retriever_Spots.php(636): Dao_Base_Comment->removeComments(Array)
#3 /home/public_html/lib/services/Retriever/Services_Retriever_Base.php(238): Services_Retriever_Spots->process(Array, 2750552, 2755553, 1611402079.2626)
#4 /home/public_html/lib/services/Retriever/Services_Retriever_Base.php(339): Services_Retriever_Base->loopTillEnd(2755553, '5000')
#5 /home/public_html/retrieve.php(142): Services_Retriever_Base->perform()
#6 {main}

Finished retrieving spots.

**Comment by muis** [comment]
@Sweepr OK, that's really strange. I can't see a way where arrayKeyToInForComments still can return FALSE with this fix applied.

**Comment by Sweepr** [comment]
> 
> 
> @Sweepr OK, that's really strange. I can't see a way where arrayKeyToInForComments still can return FALSE with this fix applied.

@muis, Sorry for my mistake, turns out the files you've changed made me pull them with root:root as owner, so when i pushed changes they didn't reflect because of that.

I have added your change's into dbeng_abs.php and now retrieve run's fine without my PR.

**Comment by Sweepr** [comment]
@mesa57, if you agree we can merge this.

**Comment by mesa57** [comment]
Looks good. Should work together with you're previous changes (tested almost the same change yesterday) 😄

**Comment by Sweepr** [comment]
> 
> 
> Looks good. Should work together with you're previous changes (tested almost the same change yesterday) 😄

@mesa57, You mean this one? https://github.com/spotweb/spotweb/pull/654

https://github.com/spotweb/spotweb/pull/655 works fine also without: https://github.com/spotweb/spotweb/pull/654, now it's no longer needed.

Can you confirm that?

**Comment by mesa57** [comment]
I meant the changes which were pushed earlier to the develop branch.
Otherwise this change would be different. But it's ok like this !

**Comment by mesa57** [comment]
I meant pull request #647 
So this change is fine.

**Pull request merged**
