### PR TITLE
Remove hardcoded default username 'nzbget' for nzbget

### PR DESCRIPTION
**Pull request by buurman**
remove hardcoded default username 'nzbget' for nzbget

### CODE REVIEW

**Comment by mesa57** [comment]
@buurman Thanks.
At this moment some members are trying to merge the master with the media branch, and I think it is wise to leave a stable situation for now and not commit any changes.

Q: any reason why htmlspecialcharacters is used ? Are user-id's like Änström>< possible ?

**Comment by buurman** [comment]
@mesa57 

Ik heb geen idee waarom dit is wat het is, ik heb de code overgenomen van sabnzbd en dat werkt al enige tijd goed en stabiel. In welk opzicht verschilt media van de huidige master...?

**Comment by mesa57** [comment]
At this moment you do not need to consider the media branche.
Another question which arose with me : should the mobile template not being changed ?

**Comment by buurman** [comment]
I have never used the mobile template, not even on my cellphone/tablet(s). I can take a look if you want me to

**Comment by mesa57** [comment]
:) I know what htmlspecialcharacters are for. That's why I gave that example. Only thing I am not sure about if nzbget users can contain special characters  to be encoded.

Third issue : I see the value from user preferences are shown in the inputbox (user). But how do they get initialised in new installations ? To nothing ?

**Comment by buurman** [comment]
If its not possible in nzbget then it won't be an issue I think, people won't be able to create an invalid username so why should they enter it.

As far your question about a clean install, it's not really an issue imo but I can try a fresh install tomorrow. As the fix I used is a copy of sabnzbd code, maybe you can find out by finding out what happens with sabnzbd after a new installation

**Comment by mesa57** [comment]
sabnzbd does not need a user to execute api calls, only an api key. 
The htmlspecialcharacters is no issue, I was just wondering why as with the password they are not used.

**Comment by buurman** [comment]
I forgot all about it but this exact change has already been merged in the media branch.. :)

**Pull request merged**
