### PR TITLE
Blacklist and whitelist URL's have been moved

### PR DESCRIPTION
**Pull request by anonymouz**
The old blacklist and whitelist URL's moved from;
http://jij.haatmij.nl/spotnet/blacklist.txt
http://jij.haatmij.nl/spotnet/whitelist.txt

to:
http://jijhaatmij.hopto.me/blacklist.txt
http://jijhaatmij.hopto.me/whitelist.txt

### CODE REVIEW

**Comment by Wally73** [comment]
ah my black/white lists ;)

there is no official one anymore but these is regularly updated

**Comment by anonymouz** [comment]
@All; I've also written a wiki entry called "Fix blacklist and whitelist problems" that you can use on your exsisting spotweb install to fix this problem...

**Comment by anonymouz** [comment]
@Wally73 Keep up the great work !!! They are very important to a good spotweb experiance !!!

**Comment by mesa57** [comment]
@Wally73 Are you still maintaining these lists ?

**Comment by Wally73** [comment]
yes @mesa57

**Comment by mesa57** [comment]
Time to merge this commit then ....

**Comment by Sweepr** [comment]
Could you create a commit for the media aswell?

**Comment by Wally73** [comment]
made pull request for media branch

**Pull request merged**
