### PR TITLE
Update Dao_Base_Spot.php

### PR DESCRIPTION
**Pull request by Sweepr**
Fix for issue: https://github.com/spotweb/spotweb/issues/629 
- Sanitize query string to prevent time based and other possible SQL injections.

### CODE REVIEW

**Comment by Sweepr** [comment]
@mesa57 Please review and merge if approved.

**Comment by mesa57** [comment]
I am still busy experimenting, but this will do for now

**Comment by bousalman** [comment]
Hi There, 

I think this code will mitigate the SQL injection attacks. 
But may I ask why don't you escape the quote character at first place? it's the reason why the query was vulnerable.

**Comment by Sweepr** [comment]
If you have a different or better solution for this problem you are always welcome to create a PR for it, then we can review and test it.

**Pull request merged**
