### PR TITLE
Merge develop into master

### PR DESCRIPTION
**Pull request by mesa57**
Need this for update of synology package

### CODE REVIEW

**Comment by Sweepr** [comment]
Again styleci is complaing about some spaces. ;-0

**Comment by mesa57** [comment]
I saw that, but leave that to you 😄 
I am concentrating on getting the synology spk published.

**Comment by Sweepr** [comment]
@mesa57 , Do you want me to pull this request?

**Comment by mesa57** [comment]
If you agree, yes please !

**Comment by Sweepr** [comment]
Done!

**Pull request merged**
