### PR TITLE
Update SpotStruct_abs.php

### PR DESCRIPTION
**Pull request by klara31**
Convert last MyISAM tables to InnoDB as MyISAM will be removed from MySQL

### CODE REVIEW

**Comment by mesa57** [comment]
MyISAM is still supported in MYSQL 8.0

**Comment by klara31** [comment]
Yes it is, but it is already announced to be removed... InnoDB is a more efficient storage engine

**Comment by Sweepr** [comment]
@mesa57 

Is there any reason this cannot be merged?

**Comment by xpunkt** [comment]
InnoDB have problems to shink tables db when gone to big, this is why i use sqlite, or betteer postgresql 16.2 :)

**Pull request closed without merging**
