### PR TITLE
Conversion from FlatCacheStore to ZipCacheStore.

### PR DESCRIPTION
**Pull request by Sweepr**
Conversion from FlatCacheStore to ZipCacheStore.

https://github.com/spotweb/spotweb/issues/208

### CODE REVIEW

**Comment by GeoffreyDijkstra** [comment]
@Sweepr Did you run a speed test/compare on your local machine? Because my spotweb takes ~2 seconds longer on each page refresh, since last commits... I'll check later if it something local or because of the zip cache.

Also be aware of which tag version you release because you added 1.0 while 1.0.0 already existed. If you would install this project from composer it would die because it normalizes the version so you have two times a v1. I corrected this for you.

**Comment by Sweepr** [comment]
I didn't notice any difference.

Did you do a fresh install or onto an existing?

**Comment by Sweepr** [comment]
@GeoffreyDijkstra  about the releases, i thought because it's the first official release of the Media branch i'd call it 1.0 but for my understanding this sn't how releases work apparently.

All the other releases are based on the Master branch, the 1.4.0 is based on the Media branch.

So i'm wondering if this is the correct way to go.

**Comment by GeoffreyDijkstra** [comment]
Well, I think there is a slight communication failure and also you made a mistake than 😄 
You added the tag to the master branch, but also the media branch should be merged into master when ready. There should be only 1 branch that contains the stable code and version numbers. If there still is a big difference between those 2 branches we need to see what those changes are and how we can make 1 package of software that fits them all.

**Comment by GeoffreyDijkstra** [comment]
Or maybe you have other thoughts about this?
Because afaik the media branch only has some extra features compared to the master branch?

**Comment by Sweepr** [comment]
Hmm, that's weird because i selected the media branch, let me see if i can fix that. (was a little late when i did that)

Well merging the media and master is going to be a hell of a task, if not nearly impossible.

If we could take the collection's feature and add this to the master branch, and make sure the zipcache works on it aswell we could remove the media branch.

**Comment by GeoffreyDijkstra** [comment]
If I got some spare time the weekend I'll take a look into this. And I strongly advise against giving other branches tags because that will screw up package managers (composer) if version numbers are matching.

**Comment by GeoffreyDijkstra** [comment]
Side note: What did you merge into master than? because if I look at the previous tag 1.3.0 compared to master: https://github.com/spotweb/spotweb/compare/1.3.0...master you merged something that's equal or so (github says so) 😯

**Comment by Sweepr** [comment]
@GeoffreyDijkstra , i re-forked the spotweb into my own account and make pull that contained no change's by mistake, no harm done there.

**Comment by Sweepr** [comment]
@GeoffreyDijkstra 

untitled

That's why i called it 1.0, but 100% i choose the media branch.

?

**Comment by GeoffreyDijkstra** [comment]
@Sweepr I don't understand why you merged a pull if it is the same...

And it ain't smart to use a tag number twice (1.0 and 1.0.0) because they translate both to "1" which is confusing for package managers like composer. For now I recommend to just leave it off.

Also I start looking into merging both branches, if I have a running version I create a new branch on spotweb for testing.

**Comment by Sweepr** [comment]
@GeoffreyDijkstra, Ok.

Did you have time to look at the picture i posted above? i've selected Media fork so why does it say there a duplicate tag for that branch then because there shouldn't be any, and even more strange is the fact that Github decided on it's own to put the release under the Master branch?

I really do not understand that at all.

**Comment by GeoffreyDijkstra** [comment]
No you cannot have the same tag twice, because in general a branch is nothing more than a path. A tag will not be added to a branch but to a commit, so selecting media or master branch means adding it to the latest commit inside that branch. That's why it's less confusing to just add tags to only the master branch, however sometimes people do tag different branches with beta or rc tags to indicate that it will be a new release for the master branch and not running into the issue of having duplicate tags. But imho just don't do it ;) Only add tags to master, you can add a rc or beta tag to that 2 so, i hope this makes it a little more clear?

**Comment by GeoffreyDijkstra** [comment]
@Sweepr For now I removed the release, because it's the same as 1.3.0 which is pointless.

**Comment by Sweepr** [comment]
I understand that you cannot have the same tag twice, but Master and Media are different branch's so imho so are the releases created for them, so i think it's rather strange you cannot make a release for different branch under that branch.

**Comment by GeoffreyDijkstra** [comment]
I understand you, but it's how git works. So you have to live with it 😄 
But if all works out, we will have only 1 branch at the end, so this problem will solve itself then 😄

**Comment by Sweepr** [comment]
@GeoffreyDijkstra Hopefully yes, but there's alot of work to be done.

**Comment by dsadsdadsadsadsds** [comment]
> @Sweepr Did you run a speed test/compare on your local machine? Because my spotweb takes ~2 seconds longer on each page refresh, since last commits... I'll check later if it something local or because of the zip cache.

This should not be possible from just the ZippedCacheStore. Some explanation:

* SpotWeb uses something called Basic Spots and Full Spots
* Basic spots are the same as other Spotnet clients use, and is basically just a small part of the headers (contained in the XOVER command from usenet servers) 
* Full Spots basically are the full headers, parsed XML and the image(s), full comments and any additional attachments to a spot (like NZB files or something like those). 

Some part of thos full spots are stored into the database (the appropriately named ```spotsfull``` table), other parts are stored on disk (the cache store). 

As you can see from my explanation, it is not possible that the listing of a spot is substiantally slower when using the ZippedCacheStore as it is not used in the listing.

There is one exception if all these conditions are true:
1. You have "Image previews" enabled (default in newer versions for logged in users)
2. Someone messed an earlier merge up and we still load the image previews synchronously

If this is true, Spotweb will include `````` tags for each and every spot in the listing, and those have to be unpackd and loaded by the ```?page=getspotimage``` handler. 

But if the async loading of images is not merged correctly, it should be done ASAP and that would fix the issue altogether.

**Pull request merged**
