### PR TITLE
Second attempt at issue #65

### PR DESCRIPTION
**Pull request by zrtq**
Here is my second attempt at fixing #65 . So far, this has fixed it for me.

Based on this comment: http://stackoverflow.com/a/3667905 , it seems like the openssl errors need to be cleared before reading and writing.

This commit adds a new function _clearSSLErrors and is called before each read and write.

### CODE REVIEW

**Comment by mesa57** [comment]
Interesting. The problem was introduced somewhere between php 5.5.21 and 5.5.23
You're fix of course doen't cure the root cause, but maybe can help.
I will look further into it.

**Comment by mesa57** [comment]
Observation : if I use php 5.4, the SSL errors still occur but do not lead to errors in the fgets() call. That one returns the expected response despite of the errors on the openssl error stack.

**Comment by zrtq** [comment]
The SSL errors must not be critical, otherwise fgets would have failed with 5.4 and with this patch.
This patch is still fixing the issue for me. There are no longer any failures while retrieving.

**Comment by mesa57** [comment]
I agree the patch solves it. 
However, it is not necessary to clear the errors before fread or fwrite.
Just before the fgets is sufficient. 
I pinpointed the problem to php release 5.5.23. In 5.5.22 it does not occur.
There were some heavy changes in \ext\openssl\xp_ssl.c due to timeout problems.

**Comment by zrtq** [comment]
Do you want me to re-submit it then so it only clears the errors before the fgets?

**Comment by mesa57** [comment]
No, Give me some time to do some more research. Maybe i'll find where those openssl warnings/errors are coming from. 
Also : the changes which you apply are in a vendor module : PEAR net_NNTP
Basicly they should do the change, or accept it as proposed.

**Comment by zrtq** [comment]
Ok. I submitted a pull request upstream: https://github.com/pear/Net_NNTP/pull/2 . I changed the patch to clear the errors before and after both fgets calls since the comment on this page: http://php.net/manual/en/function.openssl-error-string.php suggests that.

**Comment by mesa57** [comment]
Wow, the last time we've reported that issue there is was denied because we use an older fork.
But testing showed that even with the latest commit from Net-NNTP, the issue was still presemt. However they did not respond to my request to reopen the issue.
I am very curious how they will respond to you're pull request :)

**Comment by mesa57** [comment]
Another issue with this patch is that you cannot expect everyone to have openssl installed or activated ?

**Comment by zrtq** [comment]
I think that it would be best to clear the SSL errors in spotweb for now. PEAR net_NNTP and PHP developers may take a while to respond. It would be a good idea to report the issue to PHP, but even if they do fix it in the near future, it will take a long time for the new version to show up in OS releases.

**Comment by mesa57** [comment]
Ok, agreed. Going to merge.

**Comment by heino** [comment]
For the record, the reported bug at pear.php.net (http://pear.php.net/bugs/bug.php?id=20941) was not _'denied'_. The bug was rightly closed as bogus, since the referenced code was a modified fork of the package.

Based on the bug report - which only included a minimal backtrace - it was suggested to look into fgets(), by removing the prefixed @ and retrieve error messages after the function call. But due to no further comments whatsoever, the bug report was thus assumed to relate to only a single case of connection instability.

Months later @mesa57 suggested the bug should be reopened, but that comment had not caught my attention. As for @zrtq's pull request I was not even aware of it until recently, since I had no relation to the repository on GitHub, and thus was not noticed...

**The pull request https://github.com/pear/Net_NNTP/pull/2 has now been merged.**

**Pull request merged**
