### PR TITLE
Enable q and imdbid for movie search, also use q for normal search

### PR DESCRIPTION
**Pull request by onedr0p**

### CODE REVIEW

**Comment by onedr0p** [comment]
Yes it is already supported, but adhereing to the newznab api docs is good for anyone integrating your app into theirs. Sorry just being scrupulous.

**Comment by mesa57** [comment]
Fine, but by publishing capability's, as you're change does, the API should support them.
Newznab consumers depend on the t=caps api call to decide what they are going to use or not.

**Comment by onedr0p** [comment]
What changes do you want me to make? This just makes it so we know what's available for the caps.

**Comment by mesa57** [comment]
There is no need to change the caps for a normal search. More parameters are supported there.
For movie search only the imdbid parameter is available (and required).

**Pull request closed without merging**
