### PR TITLE
Make server base url scheme insensitive

### LINKED ISSUE #176: Running spotweb on HTTPS reverse proxy, spotweb internal URL's point to HTTP
This results in no CSS, no JS, because all these URL's are being called with HTTP and the most recent browsers refuse to mix HTTP on HTTPS. See screenshot. 
When I click on "Change preferences" it opens the page with HTTP and then the CSS/JS is loaded, but at this point the connection is not secure...

### PR DESCRIPTION
**Pull request by piejanssens**
Solves potential problems with reverse proxy offloading SSL
Tested on all major browsers (IE, FF, Chrome, Safari).

Fixes #176

### CODE REVIEW

**Comment by mesa57** [comment]
This not only has to be tested with different browsers, but also with different servers (apache, IIS, nginx).
At this moment I don't have the time for that,

**Comment by piejanssens** [comment]
All these servers support this. It's a standard...
Referred to as "Protocol relative URL", officially “network-path reference” according to RFC 3986.

**Comment by Sweepr** [comment]
If the image/nzb/spotdata isn't "yet" stored locally using cache, spotweb tries to fetch it from the USP, if for some reason all connection's are used it cannot fetch (hence -> error), this could also be caused by rate-limiting by the USP itself altough this is rare

**Comment by Sweepr** [comment]
Sorry commented to the wrong issue..

**Comment by mesa57** [comment]
@GeoffreyDijkstra : I think we have to revert this pull because of issue https://github.com/spotweb/spotweb/issues/197

What's you're opinion ?

**Comment by GeoffreyDijkstra** [comment]
@mesa57 It looks like it's caused by this, but I'm not sure. However the use of '//' is a standard (RFC) so such a change should not have impact. Maybe you got time to dive into this issue?

**Comment by mesa57** [comment]
Change breaks clients, reverting.

**Comment by LeeThompson** [comment]
So you undo broken code for different broken code.

Why not make variables like PROXY_HOST and PROXY_PROTOCOL that could be used in configurations that need it and just default to the original behavior if they aren't defined.     But whatever, it's your project.

**Comment by mesa57** [comment]
This is the second time a pull broke spotweb.
I am fine with any solution, if it is tested properly.

**Comment by piejanssens** [comment]
To repeat myself: "Referred to as "Protocol relative URL", officially “network-path reference” according to RFC 3986. "

This PR didn't break Spotweb, it broke the compatibilty of spotweb working with some server/proxy that is supporting this standard...

**Comment by mesa57** [comment]
Yeah sure, but I tested this myself and clients like firefox or IE do not support it.
Mind you that the url's are contained in the XML feed of the api call.

**Comment by piejanssens** [comment]
@mesa57 As a workaround I created a file ownsettings.php and put this in it but it's not working:
`settings['spotweburl'] = 'https://mijnhost.nl/spotweb/';`

**Comment by barry-luijten** [comment]
I had to add this entry to ownsettings.php as well before I was able to log in:
`$settings['cookie_host'] = 'yourhostname.com';`

**Comment by LeeThompson** [comment]
I'm going to be poking around my own copy of the code to try to make Spotweb more friendly to reverse proxy and other special installations.  I have some experience with this (actually newznab's reverse proxy support was contributed in part by me) - I'll be testing it thoroughly though before I do a pull request.   

Although if anyone wants to help test, I will update this issue with a link to my fork for testing when it's ready.    (My own environment is IIS 7.5 internet facing with an Apache 2.4 backend.)

**Comment by GeoffreyDijkstra** [comment]
@LeeThompson It would be great if we can fix this for spotweb and I volunteer for this. But my I do not understand what the exact problem is. If setup a few reverse proxies myself in the past and never run into trouble. So can you elaborate what is not working?

**Comment by LeeThompson** [comment]
@GeoffreyDijkstra 

Sure.

The problem may be the way spotweb links it's javascript and css files but I'm not sure.
Basically the search box expansion and the user preferences/settings tabs don't work properly.  (As shown in the screenshot.)    What's odd is the source view looks correct (I can even click on the script reference link in the source it it comes up), so I'm not quite sure why this is happening.    I haven't delved very deep into the javascript code itself to see if the problem might be in there somewhere.    (That's on the "to do" list.)

If you'd like to test against my server directly, maybe I can privately give you the URL.

This is what the settings screen looks like with this issue:

sample

(This case, frontend server is IIS 7.5 with url rewrite rules set up, backend server is Apache 2.4.)

**Configuration Information:**

_IIS 7.5:_

**Inbound Rule:**
```
                <rule name="ReverseProxyInboundRule1" stopProcessing="true">
                    <match url="(.*)" />
                    <conditions logicalGrouping="MatchAll" trackAllCaptures="false" />
                    <action type="Rewrite" url="http://[REDACTED: Internal URL]/{R:1}" />
                    <serverVariables>
                    </serverVariables>
                </rule>
```

**Outbound Rule:**
```
                <rule name="ReverseProxyOutboundRule1" preCondition="ResponseIsHtml1">
                    <match filterByTags="A, Area, Base, Form, Frame, Head, IFrame, Img, Input, Link, Script" pattern="^http(s)?://[REDACTED: Internal URL]/(.*)" />
                    <conditions logicalGrouping="MatchAll" trackAllCaptures="true" />
                    <action type="Rewrite" value="http{R:1}://[REDACTED: External URL]/{R:2}" />
                </rule>
```

**Preconditions:**
```
                <preConditions>
                    <preCondition name="ResponseIsHtml1">
                        <add input="{RESPONSE_CONTENT_TYPE}" pattern="^text/html" />
                    </preCondition>
                    <preCondition name="NeedsRestoringAcceptEncoding">
                        <add input="{HTTP_X_ORIGINAL_ACCEPT_ENCODING}" pattern=".+" />
                    </preCondition>
                    <preCondition name="ResponseIsNonHTML" logicalGrouping="MatchAny">
                        <add input="{QUERY_STRING}" pattern="type=css" />
                        <add input="{QUERY_STRING}" pattern="type=js" />
                    </preCondition>
                </preConditions>
```

**Comment by LeeThompson** [comment]
I may have found one of the issues with the reverse proxy url rewriting, it may be the `application/rss+xml` stream.    Will update.

**Comment by piejanssens** [comment]
@LeeThompson Soooo, is that why I don't see the downloadSabnzbd button in the UI anymore?!

**Pull request merged**
