### PR TITLE
PHP7 support for Media Branch

### PR DESCRIPTION
**Pull request by CptChaos**
I suppose this pull wil make sure Media branch has PHP7 support, see #145.
Also copied files over from master branch, I hope the changes work, so I hope a merge to master would eventually be possible too!

I also do not have much experience with git yet, so I hope someone can test my fork, before accepting the pull request?

### CODE REVIEW

**Comment by mesa57** [comment]
#cptchaos : I suppose you're repository now is the most up-to-date one for the media branch ?
Maybe @wally73 can use that repo to test ?

**Comment by CptChaos** [comment]
@mesa57 Yes, I've got two installs of Spotweb. Before I made the push, I did a pull to have the latest master branch. I checked out the media branch in another folder. Next I copied the files from the master folder over to the media folder. Next I tested and pushed the changes to my fork and did the pull request.

**Comment by mesa57** [comment]
I see strange string in you're pull request which I do not understand. Like a complete new mcreport.php which is already present in the media branche ?

**Comment by CptChaos** [comment]
Weird. I didn't change a thing actually. I just copy/pasted some files.

**Comment by CptChaos** [comment]
Ah, I missed the SABnzbd bugfix with this pull.

**Comment by dsadsdadsadsadsds** [comment]
Ah, my bad. 

I hadn't seen this PR just yet, although i think my PR is cleaner (i cherry-picked all commits from master back into the media branch, but kept the media branch specific changes).

**Pull request closed without merging**
