### PR TITLE
PHPMailer now shows error when an exception is caught.

### PR DESCRIPTION
**Pull request by Sweepr**
PHPMailer now shows error when an exception is caught.

Refactored require(); calls to work for Unix and Windows.

### CODE REVIEW

**Comment by mesa57** [comment]
Strange strange strange. This should be accomplished by composer autoload.

**Comment by mesa57** [comment]
https://getcomposer.org/doc/01-basic-usage.md#autoloading

**Comment by Sweepr** [comment]
Should be, let me check that real quick.

**Comment by Sweepr** [comment]
> 
> 
> Strange strange strange. This should be accomplished by composer autoload.

@mesa57 

One step at a time ;-)

**Pull request merged**
