### PR TITLE
security hotfixes

### PR DESCRIPTION
**Pull request by GeoffreyDijkstra**
Modified/removed htacces files because they where based on local config if apache is not configured correctly (even when it does work) SubDir htacces files might not be able to overwrite subdir htacces files.

Fix for PR #184 and issue #198

### CODE REVIEW

**Comment by GeoffreyDijkstra** [comment]
@mesa57 I removed .htaccess files from all directories / files that include web related files (css, images etc). And changed those for directories that contain only .php because those files should not be accessible by web.

**Comment by mesa57** [comment]
@GeoffreyDijkstra : I see the location of retrieve,php is changed to the bin\ folder.
This is not very sensible to do as many user have retrieve.php configured in crontab or other external tools. Could you revert that ?

**Comment by GeoffreyDijkstra** [comment]
@mesa57 I'm aware of this but sometimes you have to make a choice which users don't like. The bin folder is for CLI applications and should be shielded for the outside world (web). The largest part of the world understands that a bin folder is for binaries / executables. Also it makes your codebase more clean to have it in a standard location. However I think that we should place a warning sign somewhere to make users aware that we moved it, so we don't get 99+ issues regarding this subject tomorrow. I'll will at least update the readme so that contains the new location.

**Comment by mesa57** [comment]
Please revert, I do not want the complaints all over the place.
With spotweb you always need to take in mind that there is a large installed user base.
Only retrieve.php should go to the root folder, the rest can stay in bin

**Comment by GeoffreyDijkstra** [comment]
@mesa57 Well I think this is just an opinion but fine, I'll revert 😅

**Comment by dsadsdadsadsadsds** [comment]
Limiting install.php to localhost makes Spotweb uninstalleable for Synology (or other NAS-type) users unfortunately, perhaps this should be reconsidered.

**Pull request merged**
