### PR TITLE
NZB handling error with mobile template.

### PR DESCRIPTION
**Pull request by Sweepr**
This works as a fix for sending nzb's directly to sabnzbd/nzbget??

https://github.com/spotweb/spotweb/issues/37#issuecomment-108115956

### CODE REVIEW

**Comment by Sweepr** [comment]
@mesa57  

Can you verify if this works before i merge?

**Comment by mesa57** [comment]
I have to test this. Currently I switched to jquery.mobile-1.4.5 and getting things to work.
The NZB download link in the spot info already works.
This maybe can solve the save button working.

**Comment by mesa57** [comment]
If this works I will create a pull request together will all other changes,
For the time being I copied the code into spotinfo.php (mobile template).
But when executing I get this error : 

afbeelding

I configured a use sabnzbd via http (with api key).
So further investigation is needed.

**Comment by Sweepr** [comment]
> 
> 
> If this works I will create a pull request together will all other changes,
> For the time being I copied the code into spotinfo.php (mobile template).
> But when executing I get this error :
> 
> afbeelding
> 
> I configured a use sabnzbd via http (with api key).
> So further investigation is needed.

This has something todo with:

https://github.com/spotweb/spotweb/blob/develop/lib/SpotSecurity.php

    const spotsec_consume_api = 24;	//

https://github.com/spotweb/spotweb/blob/9374e2202f939eb2681dbbde6a823e45515e7e2e/lib/SpotSecurity.php#L49

        24		 => 'Use Spotweb using an API key',

https://github.com/spotweb/spotweb/blob/9374e2202f939eb2681dbbde6a823e45515e7e2e/lib/SpotSecurity.php#L98

**Comment by mesa57** [comment]
Ha, no. Forgot to copy some code.
Seems to work now, nzb is send to sabnzbd. 
Still need to test an other situation.
Also want to limit the number of jquery .js files

As to logon / logout : for now I placed a logout button on the screen.
When logged out, default template is we1rdo which contains a login button. So I don't see the added value for login function on mobile.

**Pull request closed without merging**
