### PR TITLE
Changes to support PHP 8.1 / Updated PHPMailer  / minor fixes.

### PR DESCRIPTION
**Pull request by Sweepr**
PHPMailer 6.5.3 contains:

    Official support for PHP 8.1
    Experimental support for PHP 8.2
    Fix for PHP 5.6

### CODE REVIEW

**Comment by mesa57** [comment]
Can you explain to me why changes are needed in spotstruct code ?
And if needed, not for pgslq and sqlite ?

**Comment by Sweepr** [comment]
> Can you explain to me why changes are needed in spotstruct code ? And if needed, not for pgslq and sqlite ?

Did not have time to test PgSQL and SQlite yet, i'll try  later.

**Comment by Sweepr** [comment]
> Can you explain to me why changes are needed in spotstruct code ? And if needed, not for pgslq and sqlite ?

Main reason is that in PHP 8.1 for certain functions passing `null` to parameter of type string is deprecated, thus i did a conversion `if (is_null($variable)) { $variable= ''; }`

https://php.watch/versions/8.1/internal-func-non-nullable-null-deprecation

**Comment by mesa57** [comment]
I agree that this is a quick fix. But I think it would be better to make sure NULL is not passed to the function as parameter (instead use an empty string).

**Comment by Sweepr** [comment]
> I agree that this is a quick fix. But I think it would be better to make sure NULL is not passed to the function as parameter (instead use an empty string).

That would be the best, and basically that would mean renaming all `null` entries in https://github.com/spotweb/spotweb/blob/9e53a0304b629c43ab1492a64450f426bff9b2d9/lib/dbstruct/SpotStruct_abs.php with `"''"` right?

**Comment by mesa57** [comment]
Ok. Of course that can only be done if NULL has the same meaning as '' (for a string)
And that maybe not the always the case (i am not sure).
Could you perhaps try to declare a parameter as type Mixed ? Mixed does allow null to passed as well as strings.....

**Comment by mesa57** [comment]
I see that:
1) It is only about checking the default value for a column 
2) That there is a difference between null and '' for a column in mysql
3) That MariaDB >= 10.4 returns the string 'NULL' if a column has default value null
4) That for mariadb that string is converted into null

So we could turn things around.
- Return 'NULL' as default (string) for mysql and leave untouched for mariadb
- Call the column check functions with 'NULL' (string) instead of null

**Comment by mesa57** [comment]
Ehhh. why did you close this ?

**Comment by Sweepr** [comment]
There was a new merge from wetsendorp, an i am still trying some things.. i will push again to my branch with the latest merge of westendorp tomorrow.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
