### PR TITLE
Overlooked a possible negative value

### PR DESCRIPTION
**Pull request by GieltjE**

### CODE REVIEW

**Comment by mesa57** [comment]
Can you update spotstruct also for the other dbms's ?

**Comment by mesa57** [comment]
Upgrading of the database takes hours (unacceptable) and also fails : 
```
D:\projects\spotweb>"C:\Program Files (x86)\iis express\PHP\v7.0\php.exe" bin\upgrade-db.php
Updating schema..(pdo_mysql)
Performing index upgrade


SpotWeb crashed

Database schema or settings upgrade failed:
   42000: 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF EXISTS
 `grouppermissions_ibfk_1`' at line 1


#0 D:\projects\spotweb\lib\dbstruct\SpotStruct_abs.php(314): dbeng_pdo->rawExec('ALTER TABLE `gr...')
#1 D:\projects\spotweb\lib\services\Upgrade\Services_Upgrade_Base.php(42): SpotStruct_abs->updateSchema()
#2 D:\projects\spotweb\bin\upgrade-db.php(34): Services_Upgrade_Base->database()
#3 {main}
D:\projects\spotweb>
```
I am afraid I have revert this pull request and the previous one.
Glad that its only the develop branch :(

**Comment by GieltjE** [comment]
It is possible that it doesn't detect the userid in all places.
As it's linked to the others it could fail, please check your DB manually and change it. (changing back would take hours again).

**Comment by mesa57** [comment]
If failed in the first step, so the database is untouched.

**Comment by GieltjE** [comment]
Which DB and version?

**Comment by mesa57** [comment]
MySql 5.5

**Pull request merged**
