### PR TITLE
Update jQuery, jQuery UI and jQuery Mobile

### PR DESCRIPTION
**Pull request by foebaz**
This pull request updates jQuery, jQuery UI and jQuery Mobile to the latest versions. The process was relatively easy for the *we1rdo* template and only minor changes were required. The most notable change is probably the removal of `jquery-json`. Basically the `jQuery.parseJSON` calls have been replaced with `JSON.parse`. `jquery-address` was updated because the old version did not work with jQuery 3.4.1. Most work went into making the *mobile* theme compatible with jQuery Mobile 1.5.0-rc1. It actually required me to rewrite some of the functionality. I don't use it myself, but since I didn't want to depend on multiple jQuery versions I went ahead and did the work. I stayed as close to the original as possible and everything works in my tests. I also switched the login page of the mobile theme to use the jQuery and jQuery Mobile versions hosted by user as opposed to using versions hosted on jquery.com, which is probably not what the user wants.

Everything works as expected in my tests, please consider pulling these changes. Thank you.

### CODE REVIEW

**Comment by mesa57** [comment]
Is there any added value for the functionality with this update ?

**Comment by foebaz** [comment]
Hi @mesa57. I should have described why I upgraded the jQuery versions (and one or two other things) instead of just stating what I did. Sorry about that.

1. I was planning on breathing new life into the *spotweb* Debian package. One of the things that the package does is use the system jQuery libraries, but the versions in Debian stable are not backwards-compatible with the "outdated" versions currently found in Spotweb. That is my initial motivation. I was planning on patching just enough, but depending on two separate jQuery versions for the package (mobile vs. full) didn't seem like the best idea.
2. Versions before jQuery 3.4.1 have known security vulnerabilities. As do jQuery UI versions before 1.12.
3. The login page for the mobile theme depends on jQuery versions hosted on jquery.com, which might not be what users want as it discloses information.

Once I updated the mobile theme, I thought I'd try to get the changes upstream into Spotweb as it updates Spotweb to 2019 as far as jQuery is concerned (the versions currently used are about 7 years old).

Hope you'll consider pulling my changes.

**Comment by mesa57** [comment]
Sure, but could you please pull back this request and resubmit it against the DEVELOP branche ?

**Comment by mesa57** [comment]
Sure, but could you please pull back this request and resubmit it against the DEVELOP branch ?

**Comment by foebaz** [comment]
Sure. No problem. I'll rebase and resubmit. Thanks.

**Comment by mesa57** [comment]
Looks like this change has broken the desktop interface (try the back button on a spot).
If so I will have to revert this change.

**Pull request closed without merging**
