### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mesa57**
Correction on name in lib/services/MediaInformation/Services_MediaInformation_Imdb.php

### CODE REVIEW

**Comment by mesa57** [comment]
Change it to uppercase I 
Strange thing is that it apparently doesn't matter for php

**Comment by mesa57** [comment]
@Sweepr Could you check and merge the pull request ?

**Comment by Sweepr** [comment]
Yes when i find the time

**Comment by Sweepr** [comment]
> 
> 
> @Sweepr Could you check and merge the pull request ?

I see 2 things, not sure if its a big deal or not but:

**Comment by mesa57** [comment]
Could you advise how to continue ?

**Comment by Sweepr** [comment]
> 
> 
> Could you advise how to continue ?

Think first would be to get you branch even with spotweb:develop, then see if we still need boxcar?

If not, ditch it can remove from the composer.

**Comment by mesa57** [comment]
There is still  an option to use boxcar. I would like to remove that, but that should be a seperate change request. For now I only want to correct the imdb interface.

**Comment by Sweepr** [comment]
> 
> 
> There is still an option to use boxcar. I would like to remove that, but that should be a seperate change request. For now I only want to correct the imdb interface.

Sure, no problem, we can check that later.

The two commits behind on your branch are these:

image

**Comment by Sweepr** [comment]
Guess we can merge it with the current develop, the 2 commits are minor.

**Comment by mesa57** [comment]
I alway sync my branch before I start changing, but apparently i was 1 day to soon with that.
Thanks for merging.

**Comment by Sweepr** [comment]
> 
> 
> I alway sync my branch before I start changing, but apparently i was 1 day to soon with that.
> Thanks for merging.

No problem, i hit my head on the same things too many times..

**Pull request merged**
