### PR TITLE
Removed tests directory

### PR DESCRIPTION
**Pull request by GeoffreyDijkstra**
There where a lot non-existing classes / issues in the tests directory so I choose to delete them for now.
If we ever need to create new tests again it's good to start over.

@mesa57 @Sweepr @mbirth What's your opinion about this?

### CODE REVIEW

**Comment by mbirth** [comment]
We definitely *should* implement tests again and the deleted ones are a good starting point. But yes, in their current state they're useless and can be removed.

**Comment by mesa57** [comment]
Who is going to test this in all kinds of environment ?
I don't have the time this week.

**Comment by dsadsdadsadsadsds** [comment]
those were not tests but utilities. CopyFilter.php is something which was sometimes recommended in the issue list in the early days and testScraper is something which contained very interesting code :-)

**Comment by GeoffreyDijkstra** [comment]
@dsadsdadsadsadsds Well, then it shouldn't have been in a `tests` directory in the first place.

**Pull request merged**
