### PR TITLE
Update settings.php

### PR DESCRIPTION
**Pull request by robertobadjo**
extra erotica category for sending to sabnzbd

### CODE REVIEW

**Comment by mesa57** [comment]
IMDB media information is already taken care of in last hotfix-403
I will look why you changed setting and maybe include that in a next release.
Meanwhile I will not merge this pull request.

**Comment by robertobadjo** [comment]
I saw that you fixed the IMDB connection.

settings.php io changed and added the erotica category if people want to filter it out with sabnzbd.

**Comment by Sweepr** [comment]
@mesa57 

Is this pull request still needed? or should it just be closed.

**Comment by mesa57** [comment]
Exactly, so after my holiday I would like to take a look at it if it can be seperatly done.
As a reminder i've not closed it yet.

**Comment by robertobadjo** [comment]
@Sweepr:

I suggested to add the erotica category to make it possible to filter out in sabnzbd or other download client. I use that setting for years now. Dont want this erotica being downloaded in my download clients

**Comment by Sweepr** [comment]
@robertobadjo

I understand, will see when @mesa57 is back from holiday to implement this option.

**Comment by Sweepr** [comment]
@mesa57 this pull is still open, do you want to merge this of does it need some extra attention?

**Pull request merged**
