### PR TITLE
Replace invalid symlinks with correct files

### PR DESCRIPTION
**Pull request by bolderbast**
Very first time contributing via github. Please be gentle. ;-)

Fixes the following errors while cloning on some file systems (like XFS):

error: unable to create symlink vendor/bin/php-coveralls: File name too long
error: unable to create symlink vendor/bin/phpcbf: File name too long
error: unable to create symlink vendor/bin/phpcs: File name too long
error: unable to create symlink vendor/bin/phpunit: File name too long

Fixes issues:
https://github.com/spotweb/spotweb/issues/749
https://github.com/spotweb/spotweb/issues/845

### CODE REVIEW

**Comment by Sweepr** [comment]
@mesa57 , could you review this and merge if Ok?

Seems a up push some time ago made sym-links out of these files, see: https://stackoverflow.com/questions/18411200/git-unable-to-create-symlink-file-name-too-long

**Comment by mesa57** [comment]
Should this not being resolved via composer ?

**Comment by mesa57** [comment]
Can you please comment on the last commit ?

**Comment by bolderbast** [comment]
> Can you please comment on the last commit ?

Scrutinizer check failed for my initial commit(s) because the new files were not executable. So made the files executable and added the commit. Scrutinizer check now passed.

**Pull request merged**
